version: '3'

services:
  app:
    container_name: app
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    env_file:
      - .env
    links:
      - "postgresql:postgresql"
  
  postgresql:
    container_name: postgresql_test
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${postgresql_dev_name}
      POSTGRES_PASSWORD: ${postgresql_dev_pass}
    env_file:
      - .env
    restart: always
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgAdmin4
    ports:
      - 8888:80
    volumes:
      - pgAdmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin4_username}
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin4_password}
    depends_on:
      - postgresql
    restart: always
  
  web:
    container_name: Nginx
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log
    ports:
      - 80:80
    environment:
      - TZ="Asia/Tokyo"
      
volumes:
  pgAdmin_data:
  postgres_data: